#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gameplay.h" //includes gba.h and font
#include "menubackground.h"
#include "gtlogo.h"
#include "d7.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

enum gba_state {
  INIT,
  START_ANIMATION,
  START_MENU,
  DRAW_PLAYSCREEN,
  READY_SET_GO,
  INIT_PLAY,
  PLAY,
  CLEARING_LINES,
  REDRAW_BOARD,
  LOSE,
  DONE
};

int main(void) {
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;

  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = INIT;

  int frames = 0;
  int onGroundFrames = 0;
  u16 shade = BLACK;

  int lines = 0;
  int linesBusted = 0;
  int level = 1;
  int score = 0;
  char strScore[6];
  int tickSpeed = 0;
  int tickSpeeds[] = {48, 40, 34, 29, 26, 23, 20, 17, 14, 12, 10, 8, 7, 6, 5, 4, 3, 2, 1};
 
  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) { //reset game
      drawRectDMA(0, 0, WIDTH, HEIGHT, BLACK);
      state = INIT;
    }

    switch (state) {
      case INIT:
        frames = 0;
        onGroundFrames = 0;
        lines = 0;
        linesBusted = 0;
        level = 1;
        score = 0;
        sprintf(strScore, "%d", 0);
        tickSpeed = 0;
        break;
      case START_ANIMATION:
        frames++;
        break;
      case START_MENU:
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
            state = DRAW_PLAYSCREEN;
            frames = 0;
        }
        break;
      case DRAW_PLAYSCREEN:
        frames++;
        break;
      case READY_SET_GO:
        frames++;
        break;
      case INIT_PLAY:
        initBoard(0);
        frames = 0;
        state = PLAY;
        break;
      case PLAY:
        if (KEY_JUST_PRESSED(BUTTON_LEFT, currentButtons, previousButtons)) {
          moveTetromino(1);
        }
        if (KEY_JUST_PRESSED(BUTTON_RIGHT, currentButtons, previousButtons)) {
          moveTetromino(3);
        }
        if (KEY_JUST_PRESSED(BUTTON_L, currentButtons, previousButtons)) {
          rotateTetromino(1);
        }
        if (KEY_JUST_PRESSED(BUTTON_R, currentButtons, previousButtons)) {
          rotateTetromino(3);
        }
        if (KEY_DOWN(BUTTON_DOWN, currentButtons)) { //soft drop
          tickSpeed = tickSpeeds[level - 1] / 12;
        } else {
          tickSpeed = tickSpeeds[level - 1];
        }
        if (KEY_JUST_PRESSED(BUTTON_A, currentButtons, previousButtons)) { //hard drop
          hardDrop(0);
          state = CLEARING_LINES;
        }
        frames++;
        if (frames % tickSpeed == 0) { //gravity
          moveTetromino(2);
        }
        if (onGround(0)) { //check if piece has been on ground for long enough to stick
          onGroundFrames++;
          if (onGroundFrames > tickSpeeds[level - 1]) {
            state = CLEARING_LINES;
            onGroundFrames = 0;
            hardDrop(0);
          }
        } else {
          onGroundFrames = 0;
        }
        break;
      case CLEARING_LINES:
        linesBusted = clearLines(0);
        if (linesBusted != 0) {
          lines += linesBusted;
          if ((lines + 1) % 8 == 0) {
            level++;
          }
          score += linesBusted * linesBusted * level * 9;
        }
        state = REDRAW_BOARD;
        frames = 0;
        break;
      case REDRAW_BOARD:
        if (frames >= 1) {
          state = PLAY;
          newPiece(0);
          if (gameOver(0)) {
            state = LOSE;
          }
        }
        frames++;
        break;
      case LOSE:
        break;
      case DONE:
        break;
    }

    waitForVBlank(0); //VBLANK BELOW (DRAW THINGS)

    switch (state) {
      case INIT:
        drawFullScreenImageDMA((u16*)menubackground); //draw background
        state = START_ANIMATION;
        break;
      case START_ANIMATION:
        drawString(HEIGHT / 5, WIDTH / 2 - 20, "TETRIS!", YELLOW);
        shade = COLOR(frames / 3, frames / 3, frames / 3);
        drawString(90, 2, "Controls:", shade);
        drawString(100, 2, "Left and Right Arrow: Move piece", shade);
        drawString(110, 2, "Down arrow: Soft drop", shade);
        drawString(120, 2, "Up arrow: Hold piece", shade);
        drawString(130, 2, "Left and Right Button (A & S): Rotate", shade);
        drawString(140, 2, "Button A (Z): Hard Drop", shade);
        drawString(150, 2, "Press START (Enter) to begin", shade);
        drawString(HEIGHT / 5 + 15, WIDTH / 2 - 60, "Made by Jonathan Luo", shade);
        if (frames >= 31 * 3) {
          state = START_MENU;
        }
        break;
      case START_MENU:
        break;
      case DRAW_PLAYSCREEN:
        switch (frames) {
          case 0:
            drawFullScreenImageDMA((u16*)menubackground);
            break;
          case 1:
            drawRectDMA(9, 84, 72, 142, WHITE);
            break;
          case 2:
            drawRectDMA(0, 85, 70, 150, BLACK); //MAIN BOARD
            break;
          case 3:
            break;
          case 4: 
            drawRectDMA(9, 156, 41, 102, WHITE); //QUEUE
            drawRectDMA(10, 156, 40, 100, BLACK);
            break;
          case 5:
            drawString(130, 160, "SCORE", WHITE);
            break;
          default:
            state = READY_SET_GO;
            frames = 0;
        }
        break;
      case READY_SET_GO:
        shade = COLOR(31 - (frames / 2) % 32, 31 - (frames / 2) % 32, 0);
        if (frames <= 62) {
          drawString(HEIGHT / 2 - 5, WIDTH / 2 - 16, "READY", shade);
        } else if (frames <= 124) {
          drawString(HEIGHT / 2 - 5, WIDTH / 2 - 10, "SET", shade);
        } else {
          drawString(HEIGHT / 2 - 5, WIDTH / 2 - 10, "GO!", shade);
        }
        if (frames > 187) {
          drawRectDMA(10, 85, 70, 140, BLACK);
          state = INIT_PLAY;
        }
        break;
      case INIT_PLAY:
        break;
      case PLAY:
        if (frames < 10 || frames % 40 == 0) {
          refreshPrevRows(0);
        }
        drawString(140, 160, strScore, BLACK);
        sprintf(strScore, "%d", score);
        drawString(140, 160, strScore, WHITE);
        break;
      case CLEARING_LINES:
        break;
      case REDRAW_BOARD:
        drawBoard(0, BOARD_HEIGHT - 1);
        if (lines > 4) {
          drawImageDMA(2, 2, GTLOGO_WIDTH, GTLOGO_HEIGHT, gtlogo);
        }
        break;
      case LOSE:
        drawFullScreenImageDMA((u16*) d7); //draw background
        drawString(HEIGHT / 2 - 20, WIDTH / 2 - 30, "GAME OVER!", YELLOW);
        state = DONE;
        break;
      case DONE:
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}
